# Generated by Django 2.2 on 2019-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tell',
            field=models.CharField(default='--', max_length=20),
            preserve_default=False,
        ),
    ]
